/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendaderopa.vistas;

import com.mycompany.tiendaderopa.servicios.*;

/**
 *
 * @author Simon Cardona
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        IClienteRepository clienteRepository = new ClienteRepository();
        IProductoRepositorio productoRepository = new ProductoRepositorio();
        IVentaRepositorio ventaRepository = new VentaRepositorio();

        ClienteService clienteService = new ClienteService(clienteRepository);
        ProductoServicio productoService = new ProductoServicio(productoRepository);
        VentaServicio ventaService = new VentaServicio(ventaRepository, clienteRepository);

        // Clientes
        tabPrincipal.setComponentAt(0, new ClientePanel(clienteService));

        // Productos
        tabPrincipal.setComponentAt(1, new ProductoPanel(productoService));

        // Ventas
        tabPrincipal.setComponentAt(2, new VentaPanel(ventaService));

        // Historial
        tabPrincipal.addTab("Historial", new HistorialPanel(ventaService));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPrincipal = new javax.swing.JTabbedPane();
        tabClientes = new javax.swing.JTabbedPane();
        tabProductos = new javax.swing.JTabbedPane();
        tabVentas = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPrincipal.addTab("Clientes", tabClientes);
        tabPrincipal.addTab("Productos", tabProductos);
        tabPrincipal.addTab("Ventas", tabVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, 1000)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 450, 450)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabClientes;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTabbedPane tabProductos;
    private javax.swing.JTabbedPane tabVentas;
    // End of variables declaration//GEN-END:variables
}
